# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    driver: "gd"
    default_filter_set_settings:
        format: webp
    filter_sets:
        cache: ~       
        thumbnail:
            quality: 75
            format: webp
            filters:
                thumbnail: { size: [120, 90], mode: inset }
        scale_photo:
            filters:
                downscale:
                    max: [400, 400]
                watermark_image:
                    image: '\public\images\watermark.png'
                    size: 0.5
                    position: center
                    alpha: 0.1        
        watermark:
            quality: 75
            format: webp
            filters:
                watermark_image:
                    image: '\public\images\watermark.png'
                    size: 0.5
                    position: multiple
                    alpha: 0.1
                upscale:
                    min: [700, 1000]
                thumbnail: 
                    size: [565, 800]
                    mode: outbound 

